[project]
name = "nrf-impact-assessor"
version = "0.2.0"
description = "nrf-impact-assessor"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.5",
    "alembic-postgresql-enum>=1.10.0",
    "asgi-logger==0.1.0",
    "aws-embedded-metrics==3.5.0",
    "boto3==1.43.63",
    "cachetools>=5.3.0",
    "dnspython==2.8.0",
    "ecs-logging==2.3.0",
    "email-validator>=2.3.0",
    "fastapi==0.141.1",
    "geoalchemy2>=0.20.0",
    "geopandas>=1.1.4",
    "moto>=5.2.2",
    "notifications-python-client>=12.1.0",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings==2.14.2",
    "pymongo[aws,encryption,snappy,zstd]==4.17.0",
    "python-multipart>=0.0.32",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2.0.51",
    "typer>=0.26.8",
    "uvicorn==0.52.0",
]

[dependency-groups]
dev = [
    "moto[s3,sqs]>=5.2.2",
    "httpx==0.28.1",
    "pre-commit==4.6.1",
    "pytest==9.1.1",
    "pytest-asyncio==1.4.0",
    "pytest-cov==7.1.0",
    "pytest-mock>=3.15.1",
    "ruff==0.16.0",
    "taskipy==1.14.1",
    "boto3-stubs==1.43.62"
]


[tool.taskipy.tasks]
dev = "bash -c 'export GIT_HASH=$(git rev-parse HEAD) MONGO_URI=${MONGO_URI:-mongodb://localhost:27018/} DB_HOST=${DB_HOST:-localhost} DB_PORT=${DB_PORT:-5432} && uvicorn app.main:app --host 0.0.0.0 --port 8085 --reload'"
format = "uv run ruff format . && uv run ruff check . --fix --exit-zero"
